# Generated by Django 5.0.3 on 2024-03-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faker',
            new_name='Employee',
        ),
    ]
